kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    app.openshift.io/route-disabled: 'false'
    deployment.kubernetes.io/revision: '6'
    image.openshift.io/triggers: >-
      [{"from":{"kind":"ImageStreamTag","name":"bitbucket-server:latest","namespace":"cp4i-arb-mig"},"fieldPath":"spec.template.spec.containers[?(@.name==\"bitbucket-server\")].image","pause":"false"}]
    openshift.io/generated-by: OpenShiftWebConsole
  name: bitbucket-server
  namespace: cp4i-arb-mig
  labels:
    app: bitbucket-server
    app.kubernetes.io/component: bitbucket-server
    app.kubernetes.io/instance: bitbucket-server
    app.kubernetes.io/name: bitbucket-server
    app.kubernetes.io/part-of: arb-mig
    app.openshift.io/runtime-namespace: cp4i-arb-mig
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitbucket-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bitbucket-server
        deploymentconfig: bitbucket-server
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      volumes:
        - name: bitbucket-server-1
          emptyDir: {}
        - name: bitbucket-server-data
          persistentVolumeClaim:
            claimName: bitbucket-server
      containers:
        - resources: {}
          readinessProbe:
            httpGet:
              path: /projects
              port: 7990
              scheme: HTTP
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          name: bitbucket-server
          livenessProbe:
            exec:
              command:
                - echo
                - ok
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 7990
              protocol: TCP
            - containerPort: 7999
              protocol: TCP
          imagePullPolicy: Always
          volumeMounts:
            - name: bitbucket-server-data
              mountPath: /var/atlassian/application-data/bitbucket
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/cp4i-arb-mig/bitbucket-server@sha256:02361b9ae95e1001c39ba2b3561100a46e8d31101a61c4c9aab72205cafb667d
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
